title: Project
@extends: 
  type: default
  context: blueprints://pages 

form:
  fields:
    tabs:
      type: tabs
      active: 1

      fields:
        content:
          type: tab
          title: PLUGIN_ADMIN.CONTENT

          fields:
            xss_check:
              type: xss

            header.title:
              type: text
              autofocus: true
              style: horizontal
              label: PLUGIN_ADMIN.TITLE
            
            header.taxonomy.category:
              type: select
              ordering@: header.title
              label: Project Category
              highlight: 0
              data-options@: '\Grav\Theme\Zitron::categories'

            header.video:
              type: text
              style: horizontal
              label: Video URL

            header.img_link:
              label: Gallery image
              help: Choose which image should be shown on the gallery parent page
              ordering@: header.taxonomy.category
              type: pagemediaselect
            
            header.media_order:
              type: pagemedia
              label: Project Media

            content:
                type: markdown
                validate:
                  type: textarea